### ISSUE TITLE
Reformat Code

### ISSUE THREAD

**Issue by rimonmostafiz** [milton-kabir/SimpleChattyBot#1]
Code is not formatted. Reformat code. 

According to your project structure, you are using IntelliJ IDEA. The formatting shortcuts in Intellij IDEA are :

For Windows : Ctrl + Alt + L
For Ubuntu : Ctrl + Alt + Windows + L
For Mac : ⌥ (Option) + ⌘ (Command) + L

**Comment by rimonmostafiz** [comment]
It's important to follow and be consistent with the source code style. Here is a popular style guide to start with.
https://google.github.io/styleguide/javaguide.html

**Comment by milton-kabir** [comment]
I will try it.
