### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by rimonmostafiz** [milton-kabir/SimpleChattyBot#3]
Add `.gitignore` file to ignore unnecessary file like `.iml ` or directory like `.idea`.

**Comment by rimonmostafiz** [comment]
https://stackoverflow.com/questions/27850222/what-is-gitignore-exactly/27850270

**Comment by rimonmostafiz** [comment]
Here is a repository with a collection of useful `.gitignore` templates
https://github.com/github/gitignore

**Comment by milton-kabir** [comment]
Done!!!
